<?xml version="1.0"?>
<!-- Revolute-Revolute Manipulator -->
<robot name="rrbot" xmlns:xacro="http://www.ros.org/wiki/xacro">

  <xacro:property name="x_ch_front" value="0.06" />   <!-- Beams are square in length and width -->
  <xacro:property name="y_ch_front" value="0.016" />   <!-- Beams are square in length and width -->
  <xacro:property name="z_ch_front" value="0.005" />   <!-- Beams are square in length and width -->

  <xacro:property name="x_ch_back" value="0.025" />   <!-- Beams are square in length and width -->
  <xacro:property name="y_ch_back" value="0.05" />   <!-- Beams are square in length and width -->
  <xacro:property name="z_ch_back" value="0.005" />   <!-- Beams are square in length and width -->
  
  <!-- WHEELS -->

  <xacro:property name="wheel_rpy" value="1.55 0.0 0.0"/>
  <xacro:property name="wheel_radius" value="0.012"/>
  <xacro:property name="wheel_lenght" value="0.015"/>

  <link name="cas_wheel">
      <inertial>
        <origin xyz="0 0 ${z_ch_front/2}" rpy="${wheel_rpy}"/>
        <mass value="1"/>
        <inertia
          ixx="1.0" ixy="0.0" ixz="0.0"
          iyy="1.0" iyz="0.0"
          izz="1.0"/>
      </inertial>
      <visual>
        <origin xyz="0 0 0 " rpy="${wheel_rpy}"/>
        <geometry>
          <sphere radius="${wheel_radius}" />
        </geometry>
        <material name="">
          <color rgba="1.0 0.0 0.0 1.0"/>
          <texture filename=""/>
        </material>
      </visual>
      <collision>
        <origin xyz="0 0 0 " rpy="${wheel_rpy}"/>
        <geometry>
          <sphere radius="${wheel_radius}"/>
        </geometry>
      </collision>
    </link>

  <link name="wheel">
      <inertial>
        <origin xyz="0 0 ${z_ch_front/2}" rpy="${wheel_rpy}"/>
        <mass value="1"/>
        <inertia
          ixx="1.0" ixy="0.0" ixz="0.0"
          iyy="1.0" iyz="0.0"
          izz="1.0"/>
      </inertial>
      <visual>
        <origin xyz="0 0 0 " rpy="${wheel_rpy}"/>
        <geometry>
          <cylinder radius="${wheel_radius}" length="${wheel_lenght}"/>
        </geometry>
        <material name="">
          <color rgba="1.0 0.0 0.0 1.0"/>
          <texture filename=""/>
        </material>
      </visual>
      <collision>
        <origin xyz="0 0 0 " rpy="${wheel_rpy}"/>
        <geometry>
          <cylinder radius="${wheel_radius}" length="${wheel_lenght}"/>
        </geometry>
      </collision>
    </link>

      <link name="wheel2">
      <inertial>
        <origin xyz="0 0 ${z_ch_front/2}" rpy="${wheel_rpy}"/>
        <mass value="1"/>
        <inertia
          ixx="1.0" ixy="0.0" ixz="0.0"
          iyy="1.0" iyz="0.0"
          izz="1.0"/>
      </inertial>
      <visual>
        <origin xyz="0 0 0 " rpy="${wheel_rpy}"/>
        <geometry>
          <cylinder radius="${wheel_radius}" length="${wheel_lenght}"/>
        </geometry>
        <material name="">
          <color rgba="1.0 0.0 0.0 1.0"/>
          <texture filename=""/>
        </material>
      </visual>
      <collision>
        <origin xyz="0 0 0 " rpy="${wheel_rpy}"/>
        <geometry>
          <cylinder radius="${wheel_radius}" length="${wheel_lenght}"/>
        </geometry>
      </collision>
    </link>

  <!-- Chassis front -->
  <link name="chassis_front">
    <visual>
      <origin xyz="0 0 ${z_ch_front/2}" rpy="0 0 0"/>
      <geometry>
	<box size="${x_ch_front} ${y_ch_front} ${z_ch_front}"/>
      </geometry>
    </visual>

    <collision>
      <origin xyz="0 0 ${z_ch_front/2}" rpy="0 0 0"/>
      <geometry>
	<box size="${x_ch_front} ${y_ch_front} ${z_ch_front}"/>
      </geometry>
    </collision>

    <inertial>
      <origin xyz="0 0 ${z_ch_front/2}" rpy="0 0 0"/>
      <mass value="1"/>
      <inertia
	  ixx="1.0" ixy="0.0" ixz="0.0"
	  iyy="1.0" iyz="0.0"
	  izz="1.0"/>
    </inertial>
  </link>



  <!-- Chassis back -->
  <link name="chassis_back">
    <visual>
      <origin xyz="0 0 ${z_ch_back/2}" rpy="0 0 0"/>
      <geometry>
	<box size="${x_ch_back} ${y_ch_back} ${z_ch_back}"/>
      </geometry>
    </visual>

    <collision>
      <origin xyz="0 0 ${z_ch_back/2}" rpy="0 0 0"/>
      <geometry>
	<box size="${x_ch_back} ${y_ch_back} ${z_ch_back}"/>
      </geometry>
    </collision>

    <inertial>
      <origin xyz="0 0 ${z_ch_back/2}" rpy="0 0 0"/>
      <mass value="1"/>
      <inertia
	  ixx="1.0" ixy="0.0" ixz="0.0"
	  iyy="1.0" iyz="0.0"
	  izz="1.0"/>
    </inertial>
  </link>


  <!-- Joint between both chassises -->
  <joint name="joint_front_back" type="fixed">
    <parent link="chassis_back"/>
    <child link="chassis_front"/>
    <origin xyz="${ (x_ch_front+x_ch_back) /2} 0 0" rpy="0 0 0"/>
  </joint>

  <!-- Joint between chassis back and wheel -->
  <joint name="joint_left_wheel_back" type="continuous">
    <parent link="chassis_back"/>
    <child link="wheel"/>
    <limit lower="0.0" upper="0.0" effort="0.0" velocity="0.0"/>
    <origin xyz="0 ${y_ch_back/2+wheel_lenght/2} 0" rpy="0 0 0"/>
    <axis xyz="0 1 0" rpy="0 0 0"/>
  </joint>


  <!-- Joint between chassis back and wheel -->
  <joint name="joint_right_wheel_back" type="continuous">
    <parent link="chassis_back"/>
    <child link="wheel2"/>
    <limit lower="0.0" upper="0.0" effort="0.0" velocity="0.0"/>
    <origin xyz="0 ${-y_ch_back/2-wheel_lenght/2} 0" rpy="0 0 0"/>
    <axis xyz="0 1 0" rpy="0 0 0"/>
  </joint>

  <!-- Joint between chassis back and wheel -->
  <joint name="joint_cas_wheel_front" type="continuous">
    <parent link="chassis_front"/>
    <child link="cas_wheel"/>
    <limit lower="0.0" upper="0.0" effort="0.0" velocity="0.0"/>
    <origin xyz="0 ${-y_ch_back/2-wheel_lenght/2} 0" rpy="0 0 0"/>
    <axis xyz="0 1 0" rpy="0 0 0"/>
  </joint>

</robot>
